# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joelg/Github/ECE_520/e520_Project/project_hw/ov7670_camera/ov7670_camera.srcs/sources_1/bd/ov7670_blk_design/ip/ov7670_blk_design_processing_system7_0_0/ov7670_blk_design_processing_system7_0_0.xci
# IP: The module: 'ov7670_blk_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joelg/Github/ECE_520/e520_Project/project_hw/ov7670_camera/ov7670_camera.gen/sources_1/bd/ov7670_blk_design/ip/ov7670_blk_design_processing_system7_0_0/ov7670_blk_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov7670_blk_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/joelg/Github/ECE_520/e520_Project/project_hw/ov7670_camera/ov7670_camera.srcs/sources_1/bd/ov7670_blk_design/ip/ov7670_blk_design_processing_system7_0_0/ov7670_blk_design_processing_system7_0_0.xci
# IP: The module: 'ov7670_blk_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joelg/Github/ECE_520/e520_Project/project_hw/ov7670_camera/ov7670_camera.gen/sources_1/bd/ov7670_blk_design/ip/ov7670_blk_design_processing_system7_0_0/ov7670_blk_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ov7670_blk_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
