# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/ov7670_blk_design/ov7670_blk_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design || ORIG_REF_NAME==ov7670_blk_design} -quiet] -quiet

# IP: bd/ov7670_blk_design/ip/ov7670_blk_design_ov7670_capture_0_0/ov7670_blk_design_ov7670_capture_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design_ov7670_capture_0_0 || ORIG_REF_NAME==ov7670_blk_design_ov7670_capture_0_0} -quiet] -quiet

# IP: bd/ov7670_blk_design/ip/ov7670_blk_design_ov7670_controller_0_0/ov7670_blk_design_ov7670_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design_ov7670_controller_0_0 || ORIG_REF_NAME==ov7670_blk_design_ov7670_controller_0_0} -quiet] -quiet

# IP: bd/ov7670_blk_design/ip/ov7670_blk_design_ov7670_vga_0_0/ov7670_blk_design_ov7670_vga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design_ov7670_vga_0_0 || ORIG_REF_NAME==ov7670_blk_design_ov7670_vga_0_0} -quiet] -quiet

# IP: bd/ov7670_blk_design/ip/ov7670_blk_design_processing_system7_0_0/ov7670_blk_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design_processing_system7_0_0 || ORIG_REF_NAME==ov7670_blk_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ov7670_blk_design/ip/ov7670_blk_design_blk_mem_gen_0_0/ov7670_blk_design_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design_blk_mem_gen_0_0 || ORIG_REF_NAME==ov7670_blk_design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ov7670_blk_design/ip/ov7670_blk_design_xlconstant_0_1/ov7670_blk_design_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ov7670_blk_design_xlconstant_0_1 || ORIG_REF_NAME==ov7670_blk_design_xlconstant_0_1} -quiet] -quiet

# XDC: e:/Linux_OS_Project/ov7670_camera/ov7670_camera.gen/sources_1/bd/ov7670_blk_design/ov7670_blk_design_ooc.xdc
